### ISSUE TITLE
Publish lockfile for binary (root) crate

### ISSUE THREAD

**Issue by jeremyBanks** [jeremyBanks/0dmg#9]
Our root crate (`zerodmg`) only provides a binary target, no libraries, and so we should include the lockfile for more reproducible/reliable builds. This requires the unstable `publish-lockfile` option:

https://doc.rust-lang.org/cargo/reference/unstable.html#publish-lockfile

```toml
cargo-features = ["publish-lockfile"]

[project]
...
publish-lockfile = true
```

Our other crates, which provide library targets, won't do this.
